{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is a simple API",
    "version" : "1.0.0",
    "title" : "Simple Inventory API",
    "contact" : {
      "email" : "you@your-company.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/chinmaysoni123/test1/1.0.0",
  "tags" : [ {
    "name" : "admins",
    "description" : "Secured Admin-only calls"
  }, {
    "name" : "developers",
    "description" : "Operations available to regular developers"
  } ],
  "schemes" : [ "https" ],
  "paths" : {
    "/unassigned_orders" : {
      "get" : {
        "tags" : [ "admins" ],
        "summary" : "admin_unassigned_orders",
        "description" : "By passing  with session token you can acess the unassigned orders\n",
        "operationId" : "admin_unassigned_orders",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "you logged in sucessfully",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200"
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/login" : {
      "post" : {
        "tags" : [ "developers" ],
        "summary" : "login session",
        "description" : "By passing username and password you can login with session token\n",
        "operationId" : "login",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "e_id_or_m_no",
          "in" : "query",
          "description" : "pass an email_id or mobile number",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "password",
          "in" : "query",
          "description" : "enter a valid password",
          "required" : true,
          "type" : "string",
          "minimum" : 8
        } ],
        "responses" : {
          "200" : {
            "description" : "you logged in sucessfully",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_1"
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/profile" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "show profile",
        "description" : "By passing session token you can get the profile details\n",
        "operationId" : "profile",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "profile details fetched sucessfully",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_2"
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/edit_profile" : {
      "put" : {
        "tags" : [ "developers" ],
        "summary" : "edit profile",
        "description" : "Edit the profile details by passing a session token.\n",
        "operationId" : "profile1",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "full_name",
          "in" : "query",
          "description" : "Enter full name",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "email",
          "in" : "query",
          "description" : "Enter email",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "date_of_birth",
          "in" : "query",
          "description" : "Enter date of birth",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "full_phone_number",
          "in" : "query",
          "description" : "Enter full phone number",
          "required" : false,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Profile details successfully retrieved.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_2"
            }
          },
          "401" : {
            "description" : "Unauthorized. Invalid session token."
          },
          "500" : {
            "description" : "Internal server error. Failed to retrieve profile details."
          }
        }
      }
    },
    "/patient_details" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "fetch patient details",
        "description" : "Fetch patient details by passing session token and patient id.\n",
        "operationId" : "patient details",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "p_id",
          "in" : "query",
          "description" : "passing patient id",
          "required" : false,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Patient details successfully retrieved.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_3"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error. Failed to retrieve patient details."
          }
        }
      }
    },
    "/submit_patient_details" : {
      "post" : {
        "tags" : [ "developers" ],
        "summary" : "submit patient details",
        "description" : "Fetch patient details by passing session token and patient id.\n",
        "operationId" : "submit patient details",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "order_id",
          "in" : "query",
          "description" : "passing order id",
          "required" : false,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "patient details successfully submitted.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_4"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error. Failed to submit patient details."
          }
        }
      }
    },
    "/collect_samples" : {
      "post" : {
        "tags" : [ "developers" ],
        "summary" : "collect patient samples",
        "description" : "Collect patient samples by passing session token and order id.\n",
        "operationId" : "collect samples",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "order_id",
          "in" : "query",
          "description" : "passing order id",
          "required" : false,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "OTP sent successfully.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_5"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error. Failed to send otp."
          }
        }
      }
    },
    "/otp_for_samples" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "otp to verify samples",
        "description" : "Verify otp to samples by passing otp and session token and order id.\n",
        "operationId" : "otp for samples verification",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "order_id",
          "in" : "query",
          "description" : "passing order id",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "otp",
          "in" : "query",
          "description" : "enter otp",
          "required" : false,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "OTP verified successfully.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_6"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error."
          }
        }
      }
    },
    "/todays_list" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "todays list",
        "description" : "Todays list of analyst.\n",
        "operationId" : "todays list",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "today's list of collection.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_7"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error."
          }
        }
      }
    },
    "/rescheduled_list" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "rescheduled list",
        "description" : "Rescheduled list of analyst.\n",
        "operationId" : "rescheduled list",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "today's list of collection.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_8"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error. Failed to submit patient details."
          }
        }
      }
    },
    "/unverified_list" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "unverified list",
        "description" : "unverified list of analyst.\n",
        "operationId" : "unverified list",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "today's list of collection.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_9"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error."
          }
        }
      }
    },
    "/cancelled_list" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "cancelled list",
        "description" : "cancelled list of analyst.\n",
        "operationId" : "cancelled list",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "today's list of collection.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_10"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error."
          }
        }
      }
    },
    "/delivery_pending_list" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "delivery pending list",
        "description" : "delivery pending list of analyst.\n",
        "operationId" : "delivery pending list",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "today's list of collection.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_11"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error."
          }
        }
      }
    },
    "/delivered_list" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "delivered list",
        "description" : "delivered  list of analyst.\n",
        "operationId" : "delivered list",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "today's list of collection.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_12"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error."
          }
        }
      }
    },
    "/update_status" : {
      "put" : {
        "tags" : [ "developers" ],
        "summary" : "update status list",
        "description" : "update the status of order.\n",
        "operationId" : "update status list",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "today's list of collection.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_13"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error."
          }
        }
      }
    },
    "/select_order_type" : {
      "post" : {
        "tags" : [ "developers" ],
        "summary" : "select order type",
        "description" : "select order type.\n",
        "operationId" : "select order type",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "pick_high_priority_and_deliver",
          "in" : "query",
          "description" : "select type",
          "required" : false,
          "type" : "boolean"
        }, {
          "name" : "pick_one_and_deliver",
          "in" : "query",
          "description" : "select type",
          "required" : false,
          "type" : "boolean"
        }, {
          "name" : "pick_all_and_deliver",
          "in" : "query",
          "description" : "select type",
          "required" : false,
          "type" : "boolean"
        } ],
        "responses" : {
          "200" : {
            "description" : "select order type.",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_14"
            }
          },
          "401" : {
            "description" : "Unauthorized.Invalid session token."
          },
          "500" : {
            "description" : "Internal server error."
          }
        }
      }
    },
    "/analyst" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "analyst details",
        "description" : "By passing session token you can get the analyst details\n",
        "operationId" : "analyst",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "description" : "The session token in the format \"Bearer {token}\"",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "analyst details fetched successfully",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_15"
            }
          },
          "400" : {
            "description" : "bad input"
          }
        }
      }
    }
  },
  "definitions" : {
    "unassigned_orders" : {
      "type" : "object",
      "properties" : {
        "order_id" : {
          "type" : "string",
          "example" : "99999"
        },
        "patient_name" : {
          "type" : "string",
          "example" : "chinmay123"
        },
        "phone_number" : {
          "type" : "string",
          "example" : "8125400447"
        },
        "location" : {
          "type" : "string",
          "example" : "Puppalaguda, manikonda Hyderabad-500089"
        },
        "sample_type" : {
          "type" : "string",
          "example" : "blood"
        },
        "schedule_date_time" : {
          "type" : "string",
          "example" : "2023-05-25 20:56:07 +0530"
        },
        "status" : {
          "type" : "string",
          "example" : "unassign"
        }
      }
    },
    "first_name" : {
      "type" : "string",
      "example" : "Pavan123"
    },
    "phlebotomist_analysis" : {
      "type" : "object",
      "properties" : {
        "user_details" : {
          "$ref" : "#/definitions/phlebotomist_analysis_user_details"
        }
      }
    },
    "profile_details" : {
      "type" : "object",
      "properties" : {
        "user_details" : {
          "$ref" : "#/definitions/profile_details_user_details"
        }
      }
    },
    "submit_patient_details" : {
      "type" : "object",
      "properties" : {
        "patient_details" : {
          "$ref" : "#/definitions/submit_patient_details_patient_details"
        }
      }
    },
    "patient_details" : {
      "type" : "object",
      "properties" : {
        "patient_details" : {
          "$ref" : "#/definitions/patient_details_patient_details"
        }
      }
    },
    "collect_samples" : {
      "type" : "object",
      "properties" : {
        "message" : {
          "type" : "string",
          "example" : "Verify OTP (123456) to collect"
        }
      }
    },
    "select_type" : {
      "type" : "object",
      "properties" : {
        "pick_high_priority_and_deliver" : {
          "type" : "boolean",
          "example" : true
        },
        "pick_one_deliver" : {
          "type" : "boolean",
          "example" : false
        },
        "pick_all_and_deliver" : {
          "type" : "boolean",
          "example" : false
        }
      }
    },
    "otp_samples" : {
      "type" : "object",
      "properties" : {
        "response" : {
          "type" : "string",
          "example" : "OTP verfied successfully"
        }
      }
    },
    "todays_list_object" : {
      "type" : "object",
      "properties" : {
        "user_id" : {
          "type" : "string",
          "example" : "123"
        },
        "full_name" : {
          "$ref" : "#/definitions/first_name"
        },
        "address" : {
          "type" : "string",
          "example" : "Puppalaguda, manikonda Hyderabad-500089"
        },
        "priority" : {
          "type" : "string",
          "example" : "High Priority"
        },
        "status" : {
          "type" : "string",
          "example" : "To Be Picked"
        },
        "sample_type" : {
          "type" : "string",
          "example" : "Blood Sample"
        },
        "time" : {
          "type" : "string",
          "example" : "10:30AM"
        },
        "order_id" : {
          "type" : "string",
          "example" : "2"
        }
      }
    },
    "session" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/session_data"
          }
        }
      },
      "description" : "it gives session token"
    },
    "Phlebotomist analysis" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int64"
        }
      }
    },
    "inline_response_200_success" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/unassigned_orders"
          }
        }
      }
    },
    "inline_response_200" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/inline_response_200_success"
        }
      }
    },
    "inline_response_200_1" : {
      "type" : "object",
      "properties" : {
        "session" : {
          "$ref" : "#/definitions/session"
        }
      }
    },
    "inline_response_200_2" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/profile_details"
        }
      }
    },
    "inline_response_200_3" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/patient_details"
        }
      }
    },
    "inline_response_200_4" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/submit_patient_details"
        }
      }
    },
    "inline_response_200_5" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/collect_samples"
        }
      }
    },
    "inline_response_200_6" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/otp_samples"
        }
      }
    },
    "inline_response_200_7_success" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "example" : [ {
            "user_id" : "12",
            "full_name" : "kasa rakesh",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "To Be Picked",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "1"
          }, {
            "user_id" : "13",
            "full_name" : "Pavan reddy",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "To Be Picked",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "2"
          } ],
          "items" : {
            "$ref" : "#/definitions/todays_list_object"
          }
        }
      }
    },
    "inline_response_200_7" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/inline_response_200_7_success"
        }
      }
    },
    "inline_response_200_8_success" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "example" : [ {
            "user_id" : "12",
            "full_name" : "kasa rakesh",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "rescheduled",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "1"
          }, {
            "user_id" : "13",
            "full_name" : "Pavan reddy",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "rescheduled",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "2"
          } ],
          "items" : {
            "$ref" : "#/definitions/todays_list_object"
          }
        }
      }
    },
    "inline_response_200_8" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/inline_response_200_8_success"
        }
      }
    },
    "inline_response_200_9_success" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "example" : [ {
            "user_id" : "12",
            "full_name" : "kasa rakesh",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "unverified",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "1"
          }, {
            "user_id" : "13",
            "full_name" : "Pavan reddy",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "unverified",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "2"
          } ],
          "items" : {
            "$ref" : "#/definitions/todays_list_object"
          }
        }
      }
    },
    "inline_response_200_9" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/inline_response_200_9_success"
        }
      }
    },
    "inline_response_200_10_success" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "example" : [ {
            "user_id" : "12",
            "full_name" : "kasa rakesh",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "cancelled",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "1"
          }, {
            "user_id" : "13",
            "full_name" : "Pavan reddy",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "cancelled",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "2"
          } ],
          "items" : {
            "$ref" : "#/definitions/todays_list_object"
          }
        }
      }
    },
    "inline_response_200_10" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/inline_response_200_10_success"
        }
      }
    },
    "inline_response_200_11_success" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "example" : [ {
            "user_id" : "12",
            "full_name" : "kasa rakesh",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "delivery pending",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "1"
          }, {
            "user_id" : "13",
            "full_name" : "Pavan reddy",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "delivery pending",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "2"
          } ],
          "items" : {
            "$ref" : "#/definitions/todays_list_object"
          }
        }
      }
    },
    "inline_response_200_11" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/inline_response_200_11_success"
        }
      }
    },
    "inline_response_200_12_success" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "example" : [ {
            "user_id" : "12",
            "full_name" : "kasa rakesh",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "delivered",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "1"
          }, {
            "user_id" : "13",
            "full_name" : "Pavan reddy",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "delivered",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "2"
          } ],
          "items" : {
            "$ref" : "#/definitions/todays_list_object"
          }
        }
      }
    },
    "inline_response_200_12" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/inline_response_200_12_success"
        }
      }
    },
    "inline_response_200_13_success" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "example" : [ {
            "user_id" : "12",
            "full_name" : "kasa rakesh",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "arrived",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "1"
          }, {
            "user_id" : "13",
            "full_name" : "Pavan reddy",
            "address" : "Puppalaguda, manikonda Hyderabad-500089",
            "priority" : "High Priority",
            "status" : "arrived",
            "sample_type" : "Blood Sample",
            "date_time" : "2023-05-26T12:26:45+05:30",
            "order_id" : "2"
          } ],
          "items" : {
            "$ref" : "#/definitions/todays_list_object"
          }
        }
      }
    },
    "inline_response_200_13" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/inline_response_200_13_success"
        }
      }
    },
    "inline_response_200_14" : {
      "type" : "object",
      "properties" : {
        "response" : {
          "$ref" : "#/definitions/select_type"
        }
      }
    },
    "inline_response_200_15" : {
      "type" : "object",
      "properties" : {
        "success" : {
          "$ref" : "#/definitions/phlebotomist_analysis"
        }
      }
    },
    "phlebotomist_analysis_user_details_performance" : {
      "type" : "object",
      "properties" : {
        "total_assigned_orders" : {
          "type" : "string",
          "example" : "200"
        },
        "delivered" : {
          "type" : "string",
          "example" : "102"
        },
        "cancelled" : {
          "type" : "string",
          "example" : "100"
        },
        "preparing" : {
          "type" : "string",
          "example" : "100"
        },
        "rescheduled" : {
          "type" : "string",
          "example" : "100"
        }
      }
    },
    "phlebotomist_analysis_user_details_overview" : {
      "type" : "object",
      "properties" : {
        "medium" : {
          "type" : "string",
          "example" : "38"
        },
        "high" : {
          "type" : "string",
          "example" : "75"
        },
        "low" : {
          "type" : "string",
          "example" : "55"
        }
      }
    },
    "phlebotomist_analysis_user_details_reviews_and_ratings_rating" : {
      "type" : "object",
      "properties" : {
        "1_star" : {
          "type" : "string",
          "example" : "1"
        },
        "2_star" : {
          "type" : "string",
          "example" : "2"
        },
        "3_star" : {
          "type" : "string",
          "example" : "3"
        },
        "4_star" : {
          "type" : "string",
          "example" : "4"
        },
        "5_star" : {
          "type" : "string",
          "example" : "5"
        }
      }
    },
    "phlebotomist_analysis_user_details_reviews_and_ratings" : {
      "type" : "object",
      "properties" : {
        "average_rating" : {
          "type" : "string",
          "example" : "4.5"
        },
        "count_of_total_reviews" : {
          "type" : "string",
          "example" : "10"
        },
        "rating" : {
          "$ref" : "#/definitions/phlebotomist_analysis_user_details_reviews_and_ratings_rating"
        }
      }
    },
    "phlebotomist_analysis_user_details" : {
      "type" : "object",
      "properties" : {
        "user_id" : {
          "type" : "string",
          "example" : "123"
        },
        "profile_image" : {
          "type" : "string",
          "example" : "https://lh3.googleusercontent.com/ogw/AOLn63GYQ3uohe6sVntykFZgEXNMx93yaO0hx5Ggy9Cryw=s32-c-mo"
        },
        "full_name" : {
          "$ref" : "#/definitions/first_name"
        },
        "member_since" : {
          "type" : "string",
          "example" : "2"
        },
        "last_collection" : {
          "type" : "string",
          "example" : "3"
        },
        "performance" : {
          "$ref" : "#/definitions/phlebotomist_analysis_user_details_performance"
        },
        "overview" : {
          "$ref" : "#/definitions/phlebotomist_analysis_user_details_overview"
        },
        "reviews_and_ratings" : {
          "$ref" : "#/definitions/phlebotomist_analysis_user_details_reviews_and_ratings"
        }
      }
    },
    "profile_details_user_details" : {
      "type" : "object",
      "properties" : {
        "user_id" : {
          "type" : "string",
          "example" : "123"
        },
        "profile_image" : {
          "type" : "string",
          "example" : "https://lh3.googleusercontent.com/ogw/AOLn63GYQ3uohe6sVntykFZgEXNMx93yaO0hx5Ggy9Cryw=s32-c-mo"
        },
        "full_name" : {
          "$ref" : "#/definitions/first_name"
        },
        "date_of_birth" : {
          "type" : "string",
          "example" : "05/09/98"
        },
        "full_phone_number" : {
          "type" : "string",
          "example" : "+91 1234567890"
        },
        "gender" : {
          "type" : "string",
          "example" : "male"
        },
        "email" : {
          "type" : "string",
          "example" : "shree@gmail.com"
        },
        "password" : {
          "type" : "string",
          "example" : "password"
        }
      }
    },
    "submit_patient_details_patient_details" : {
      "type" : "object",
      "properties" : {
        "user_id" : {
          "type" : "string",
          "example" : "123"
        },
        "full_name" : {
          "$ref" : "#/definitions/first_name"
        },
        "full_phone_number" : {
          "type" : "string",
          "example" : "+91 1234567890"
        },
        "date_of_birth" : {
          "type" : "string",
          "example" : "05/08/1993"
        },
        "address" : {
          "type" : "string",
          "example" : "Puppalaguda, manikonda Hyderabad-500089"
        },
        "lab_address" : {
          "type" : "string",
          "example" : "Puppalaguda, manikonda Hyderabad-500089"
        },
        "sample" : {
          "type" : "string",
          "example" : "blood"
        },
        "priority" : {
          "type" : "string",
          "example" : "High"
        },
        "slot_timing" : {
          "type" : "string",
          "example" : "03:30AM to 04:30AM"
        },
        "started_at" : {
          "type" : "string",
          "example" : "03:30AM"
        },
        "collected_at" : {
          "type" : "string",
          "example" : "04:35AM"
        },
        "lab_submission_at" : {
          "type" : "string",
          "example" : "06:30PM"
        }
      }
    },
    "patient_details_patient_details" : {
      "type" : "object",
      "properties" : {
        "user_id" : {
          "type" : "string",
          "example" : "123"
        },
        "full_name" : {
          "$ref" : "#/definitions/first_name"
        },
        "full_phone_number" : {
          "type" : "string",
          "example" : "+91 1234567890"
        },
        "date_of_birth" : {
          "type" : "string",
          "example" : "05/08/1993"
        },
        "address" : {
          "type" : "string",
          "example" : "Puppalaguda, manikonda Hyderabad-500089"
        },
        "lab_address" : {
          "type" : "string",
          "example" : "Puppalaguda, manikonda Hyderabad-500089"
        },
        "sample" : {
          "type" : "string",
          "example" : "blood"
        },
        "priority" : {
          "type" : "string",
          "example" : "High"
        },
        "slot_timing" : {
          "type" : "string",
          "example" : "03:30AM to 04:30AM"
        },
        "started_at" : {
          "type" : "string",
          "example" : "03:30AM"
        },
        "collected_at" : {
          "type" : "string",
          "example" : "04:35AM"
        },
        "order_id" : {
          "type" : "string",
          "example" : "2"
        }
      }
    },
    "session_user" : {
      "type" : "object",
      "properties" : {
        "user_id" : {
          "type" : "string",
          "example" : "123"
        },
        "profile_image" : {
          "type" : "string",
          "example" : "https://lh3.googleusercontent.com/ogw/AOLn63GYQ3uohe6sVntykFZgEXNMx93yaO0hx5Ggy9Cryw=s32-c-mo"
        },
        "first_name" : {
          "$ref" : "#/definitions/first_name"
        },
        "location" : {
          "type" : "string",
          "example" : "Shaikpet Main Rd, Hyderabad"
        }
      }
    },
    "session_data" : {
      "type" : "object",
      "properties" : {
        "token" : {
          "type" : "string",
          "example" : "eyJhbGciOiJIUzUxMiJ9.eyJpZCI6NjQ1LCJleHAiOjE3MTYzNzE4MDF9.9Jmn5F8eFnx6tzlcJRSPyy6475t1r9mKbRR27n3f9TuyEZI0ktOPXmWOv8yqRniDcm_oFrLUr7qcnoz14YaLGA"
        },
        "user" : {
          "$ref" : "#/definitions/session_user"
        }
      }
    }
  }
}